version: '2'

services:
  app:
    image: mxssl/hello-world:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:80/tcp"

  grafana:
    image: grafana/grafana:6.0.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "0.0.0.0:3000:3000/tcp"

  prometheus:
    image: prom/prometheus:v2.7.2
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - "0.0.0.0:9090:9090/tcp"
