{
 "title": "App",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{ http requests }}" }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ Goroutines }}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[5m])",
     "legendFormat": "Cpu usage %"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ resident }}" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{ virtual }}" }
   ]
  }
 ]
}